# Generated by Django 6.0.2 on 2026-02-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='category',
            field=models.CharField(choices=[('general', 'Общие знания'), ('science', 'Наука'), ('history', 'История'), ('geography', 'География'), ('literature', 'Литература'), ('movies', 'Фильмы'), ('music', 'Музыка'), ('sports', 'Спорт'), ('technology', 'Технологии'), ('astronomy', 'Астрономия'), ('art', 'Искусство'), ('food', 'Еда и кулинария'), ('animals', 'Животные'), ('mythology', 'Мифология'), ('other', 'Другое')], default='general', max_length=20, verbose_name='Категория'),
        ),
    ]
