# Generated by Django 6.0.2 on 2026-02-08 17:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_quiz_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['category'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='quiz',
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, verbose_name='Сложность (1-5)'),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='categories',
            field=models.ManyToManyField(related_name='results', to='main.quiz', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.quiz', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='question',
            name='time_limit',
            field=models.IntegerField(default=30, verbose_name='Время на ответ (секунды)'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.CharField(choices=[('general', 'Общие знания'), ('science', 'Наука'), ('history', 'История'), ('geography', 'География'), ('literature', 'Литература'), ('movies', 'Фильмы'), ('music', 'Музыка'), ('sports', 'Спорт'), ('technology', 'Технологии'), ('astronomy', 'Астрономия'), ('art', 'Искусство'), ('food', 'Еда и кулинария'), ('animals', 'Животные'), ('mythology', 'Мифология'), ('other', 'Другое')], default='general', max_length=20, unique=True, verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='WrongAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Отвечено')),
                ('is_repeated', models.BooleanField(default=False, verbose_name='Перепройден')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrong_answers', to='main.question', verbose_name='Вопрос')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrong_answers', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Неправильный ответ',
                'verbose_name_plural': 'Неправильные ответы',
                'ordering': ['-answered_at'],
            },
        ),
    ]
