# Generated by Django 6.0.2 on 2026-02-28 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_quiz_options_remove_quizresult_quiz_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created_at'], 'verbose_name': 'Квиз', 'verbose_name_plural': 'Квизы'},
        ),
        migrations.AddField(
            model_name='quiz',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='visibility',
            field=models.CharField(choices=[('public', 'Публичный'), ('friends', 'Только друзьям'), ('private', 'Приватный (по ссылке)')], default='public', max_length=10, verbose_name='Видимость'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.CharField(choices=[('general', 'Общие знания'), ('science', 'Наука'), ('history', 'История'), ('geography', 'География'), ('literature', 'Литература'), ('movies', 'Фильмы'), ('music', 'Музыка'), ('sports', 'Спорт'), ('technology', 'Технологии'), ('astronomy', 'Астрономия'), ('art', 'Искусство'), ('food', 'Еда и кулинария'), ('animals', 'Животные'), ('mythology', 'Мифология'), ('other', 'Другое')], default='general', max_length=20, verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='pending', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Принято')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Дружба',
                'verbose_name_plural': 'Дружба',
                'unique_together': {('from_user', 'to_user')},
            },
        ),
    ]
