# Generated by Django 6.0.2 on 2026-03-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_quiz_options_quiz_updated_at_quiz_visibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_global',
            field=models.BooleanField(default=False, help_text='Если включено — квиз появится в общем списке "Начать квиз" (только для админов)', verbose_name='Глобальный квиз'),
        ),
    ]
